language: node_js
node_js:
- '0.11'
before_script:
- chmod +x deploy/deploy.sh
branches:
  only:
  - master
after_success: ./deploy/deploy.sh
env:
  global:
  - GH_REF: github.com/mumbairains/mumbairains.org.git
